### ISSUE TITLE
Bug in Flux test

### ISSUE THREAD

**Issue by tcbrindle** [serpent7776/cpp-ranges-bench#1]
Hi @serpent7776,

I'm the author of the Flux library. Unfortunately Flux didn't do very well in your recent blog post, but it seems that this might be because of a bug in the test case.

On line 246:

https://github.com/serpent7776/cpp-ranges-bench/blob/934135e7842ad1280d7c6c9e32ca3b9f858603b2/test.cpp#L244-L246

you're calling `flux::from(std::move(v))`, which tells Flux to take ownership of `v`. Unfortunately, because `v` is a `const std::vector`, it's not movable, so this is causing the whole input vector to be copied at every entry to the function!

Calling `flux::ref(v).filter(accept).take(max_items)` instead will iterate over `v` by reference, meaning no copy will be made. With this change, the timings for Flux (in my tests) are much more in line with the other libraries.

**Comment by serpent7776** [comment]
Hi, thanks for catching this and sorry for making such a stupid mistake. I should've double-checked the slow down wasn't in my code. I've updated the blog post.

**Comment by tcbrindle** [comment]
Thank you very much for the quick update!
